/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ISchemaRegistry__factory } from "./ISchemaRegistry__factory";
export { ISemver__factory } from "./ISemver__factory";
